// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc4905.AndromedaOneRobot.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc4905.AndromedaOneRobot.Robot;
/**
 *
 */
public class Stow extends Command
{
    public Stow()
    {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.armPlatform);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    // Called just before this Command runs the first time
    protected void initialize()
    {
        Robot.armPlatform.getPIDController().setOutputRange(-0.7, 0.7);
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZE
        Robot.armPlatform.enable();
        Robot.armPlatform.setSetpoint(2.2);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZE
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute()
    {
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished()
    {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ISFINISHED
        return Robot.armPlatform.onTarget();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ISFINISHED
    }
    // Called once after isFinished returns true
    protected void end()
    {
        Robot.armPlatform.disable();
        Robot.armPlatform.getPIDController().setOutputRange(-1.0, 1.0);
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted()
    {
        end();
    }
}
