// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc4905.AndromedaOneRobot.subsystems;

import org.usfirst.frc4905.AndromedaOneRobot.RobotMap;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class RobotArms extends Subsystem
{
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SpeedController armsMotor_Controller = RobotMap.robotArmsArmsMotor_Controller;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	AnalogChannel armsPot = RobotMap.robotArmsPot;

	// Put methods for controlling this subsystem
	// here. Call these from Commands.
	public void initDefaultCommand()
	{
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
		// Set the default command for a subsystem here.
		// setDefaultCommand(new MySpecialCommand());
	}

	public void closeRobotArms()
	{
		double potVal = armsPot.getAverageVoltage();
		double speed;

		if (potVal < 0.65)
			speed = 0.0;
		else
			speed = 1.0;

		armsMotor_Controller.set(speed);
	}

	public void openRobotArms()
	{
		double potVal = armsPot.getAverageVoltage();
		double speed;

		if (potVal > 1.3)
			speed = 0.0;
		else
			speed = -1.0;

		armsMotor_Controller.set(speed);
	}

	public void stopRobotArms()
	{
		armsMotor_Controller.set(0.0);
	}
}
